In [11]:
from utils_ensemble import load_ensemble_tuples
import os
import numpy as np
import glob

In [2]:
tuples = load_ensemble_tuples()

base_path = "/gpfs/wolf2/cades/cli185/proj-shared/zdr/ERW/output/UQ/pft1"

bad_ens = []
bad_folders = []
for ens in range(1, 2001):
    ens_str = f"{ens:04d}"
    pattern = os.path.join(base_path, f"*_conus_ICB20TRCNPRDCTCBC_erw_pft1_ens{ens_str}")
    dirs = glob.glob(pattern + "/")
    if not dirs:
        continue
    folder = sorted(dirs)[-1]
    file_pattern = os.path.join(folder, "run", "*.h1.*.nc")
    files = glob.glob(file_pattern)
    if len(files) < 57:
        bad_folders.append(folder)
        bad_ens.append(ens)

In [18]:
tuples.loc[bad_ens, :]

,Grain size (um),Rate (kg/m2),Start year,Frequency
55,2,2,2034,1
59,2,2,2033,1
63,2,2,2032,1
67,2,2,2031,1
71,2,2,2030,1
...,...,...,...,...
1084,20,4,2027,1
1087,20,4,2026,3
1088,20,4,2026,1
1091,20,4,2025,3


In [13]:
np.unique(tuples.loc[bad_ens, 'Grain size (um)'], return_counts = True)

(array([ 2, 10, 20]), array([223, 239,  60]))

In [16]:
np.unique(tuples.loc[bad_ens, 'Rate (kg/m2)'], return_counts = True)

(array([ 2,  4,  6,  8, 10]), array([ 59,  96, 101, 128, 138]))

In [17]:
np.unique(tuples.loc[bad_ens, 'Start year'], return_counts = True)

(array([2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035,
        2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046,
        2047, 2048, 2049, 2050]),
 array([29, 28, 29, 32, 27, 29, 27, 26, 25, 27, 26, 21, 24, 23, 20, 19, 22,
        17, 15, 14, 13, 12,  9,  5,  2,  1]))

In [12]:
np.unique(tuples.loc[bad_ens, 'Frequency'], return_counts=True)

(array([  1,   3,   9, 999]), array([251, 161,  86,  24]))